[package]
name = "seaweed"
version = "0.1.0"
edition = "2021"
authors = ["Nikita Gaevoy"]
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
num = "0.4.1"

[dev-dependencies]
zip = "0.6.6"
futures = "0.3.30"
async-std = "1.12.0"
